# This workflow will run linters using node
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node Linter

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  build: 
    name: linter
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: installer
        run: npm install

      - name: lint
        run: npm run lint
